### ISSUE TITLE
Numpy error using spams.trainDL

### ISSUE THREAD

**Issue by carversh** [getspams/spams-python#32]
Hi,

I'm running the following function:
`D = spams.trainDL(X, lambda1=0.15)`

and get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../python3.9/site-packages/spams/spams.py", line 2026, in trainDL
    return __allTrainDL(X, return_model, model, False, D, None, None, numThreads, 0.000001, True, False, batchsize, K, lambda1, lambda2, lambda3, iter, t0, mode, regul, posAlpha, posD, expand, modeD, whiten, clean, verbose, gamma1, gamma2, rho, iter_updateD, stochastic_deprecated, modeParam, batch, log_deprecated, logName)
  File "/.../python3.9/site-packages/spams/spams.py", line 1834, in __allTrainDL
    np.array([[False], [False]], dtype=np.bool, order="F"))
  File "/.../site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by carversh** [comment]
X is a numpy array, by the way

**Comment by carversh** [comment]
Presumably the pip install isn't updated for the newest version of numpy
