### ISSUE TITLE
Unable to import _spams_wrap

### ISSUE THREAD

**Issue by yizhwan** [getspams/spams-python#37]
Dear all, 

I have successfully installed spams 2.6.5.4 in a venv virtual environment on Ubuntu 22.04 using pip 23.21 in a python 3.10.12 environment. There were no errors during the installation. However, when trying to import the package, I get the following error:

Traceback (most recent call last):
  File "/home/yizhou/scilpy_new/.env/lib/python3.10/site-packages/spams_wrap/spams_wrap.py", line 22, in swig_import_helper
    fp, pathname, description = imp.find_module(
  File "/usr/lib/python3.10/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_spams_wrap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yizhou/scilpy_new/.env/lib/python3.10/site-packages/spams/__init__.py", line 6, in <module>
    from .spams import *
  File "/home/yizhou/scilpy_new/.env/lib/python3.10/site-packages/spams/spams.py", line 6, in <module>
    import spams_wrap
  File "/home/yizhou/scilpy_new/.env/lib/python3.10/site-packages/spams_wrap/__init__.py", line 6, in <module>
    from .spams_wrap import *
  File "/home/yizhou/scilpy_new/.env/lib/python3.10/site-packages/spams_wrap/spams_wrap.py", line 34, in <module>
    _spams_wrap = swig_import_helper()
  File "/home/yizhou/scilpy_new/.env/lib/python3.10/site-packages/spams_wrap/spams_wrap.py", line 25, in swig_import_helper
    import _spams_wrap
ImportError: /home/yizhou/scilpy_new/.env/lib/python3.10/site-packages/_spams_wrap.cpython-310-x86_64-linux-gnu.so: undefined symbol: dsyr2k_

Is this an issue for python 3.10? If so is there any python 3.10 compatible versions of spams available?

Thanks

**Comment by samuelstjean** [comment]
it looks like it was not correctly linked to blas/lapack, so you were probably missing it when compiling manually during install. either install it through you package manager/conda or you can use a prebuilt version here https://pypi.org/project/spams-bin/, they are built against rather generic version from memory but just work as is normally.

**Comment by yizhwan** [comment]
Thanks, I can confirm that your solution has fixed the issue.
